In [ ]:
# GeoFabrik
# https://download.geofabrik.de/europe/netherlands.html
GEOFABRIK_DATA = 'extra/data_src/provinces'

In [ ]:
# Bestuurlijke gebieden (land, provincie, gemeente)
# https://www.pdok.nl/introductie/-/article/bestuurlijke-gebieden
BESTUURLIJKE_GEBIEDEN_DATA = 'extra\data_src\cbsgebiedsindelingen2026.gpkg'

In [ ]:
# CBS Gebiedsindelingen (Gemeente Landsdeel Provincie Buurt COROP-gebied GGD-regio NUTS1 NUTS2 NUTS3 Wijk Grootstedelijke aglomeratie Stadsgewest COROP-plusgebied COROP-subgebied Landbouwgebied Landbouwgroep RPA-gebied Toeristengroep Toeristengebied Arrondissementsgebied Brandweerregio Kamer van Koophandelregio Politieregio Regionale Eenheid Veiligheidsregio Zorgkantoorregio Arbeidsmarktregio Jeugdzorgregio Ressort)
# CRS is EPSG:28992
#   SQL statement in file (download source: https://epsg.io/28992)
# https://www.pdok.nl/introductie/-/article/cbs-gebiedsindelingen
CBS_GEBIEDSINDELINGEN_DATA = 'extra\data_src\cbsgebiedsindelingen2026.gpkg'

# Import
https://skipperkongen.dk/2018/03/13/how-to-create-a-world-wide-postgresql-database-of-administrative-regions/

https://postgis.net/workshops/postgis-intro/loading_data.html#loading-data

In [ ]:
%%bash

~/Downloads/ogr2ogr.exe -f PostgreSQL "PG:dbname=dutch_railways" DNK_adm.gpkg

export PGPASSWORD=mydatabasepassword

ogr2ogr `
  -nln nyc_census_blocks_2000 ` # new layer name
  -nlt PROMOTE_TO_MULTI       ` # new layer type
  -lco GEOMETRY_NAME=geom     ` # layer create option
  -lco FID=gid \              ` #   primary key column name
  -lco PRECISION=NO \         ` #   which type for numeric fields? we turn off "numeric" (disable higher precision)
  Pg:"dbname=nyc host=localhost user=pramsey port=5432" ` # driver and connection string. options, dest, source
  nyc_census_blocks_2000.shp    # source data (can also read multiple layers at once by using connection string followed by list of layer names)

In [13]:
%%sql
-- Get text definition of spatial reference
SELECT srs_name FROM gpkg_spatial_ref_sys WHERE srs_id = 28992;

              srs_name
0  Amersfoort / RD New

In [14]:
%%sql
-- Get text definition of spatial reference
SELECT srtext FROM spatial_ref_sys WHERE srid = 28992;

                                              srtext
0  PROJCS["Amersfoort / RD New",GEOGCS["Amersfoor...

In [ ]:
%%sql
-- SELECT name_2, ST_AsText(wkb_geometry)
-- FROM dnk_adm2
-- WHERE ST_Intersects(ST_SetSRID(ST_Point(12.563585, 55.690628), 4326), wkb_geometry)
-- AND ST_Point(12.563585, 55.690628) && wkb_geometry